### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by nicewook** [nicewook/refactoring-go-exercise#1]
# Todo list

- [ ] main readme file
  - [ ] origin
  - [ ] purpose: make example from original `JavaScript` to `Go`
  - [ ] explanation of structure. usage
- [ ] check and list the steps
- [ ] code for each step
- [ ] make readme file for each step
  - [ ] what was the smell
  - [ ] what was the recipes for the smell
